### ISSUE TITLE
Rethink/restructure connections and peer state management

### ISSUE THREAD

**Issue by michaelsproul** [michaelsproul/ewok#19]
There are some sharp edges to the current model that it would be nice to remove...

Specifically, we need solutions for:

* [ ] A joining node shouldn't send its `NodeJoined` event to the whole network (#29).
* [ ] Nodes shouldn't keep peer states for peers that are no longer neighbours because of splits (#31).
* [ ] Nodes shouldn't broadcast their Votes to peers that are no longer neighbours (#22).
* [x] Messages shouldn't be dropped completely because of temporary disconnects – perhaps we can use the `Network` to re-queue them (to simulate continual resending) (#21).

In general, as @Fraser999 noticed, there seems to be a weird mismatch between the simulator having a definitive idea about who is connected to who, and nodes themselves having a local view of their connectivity... I think we either need to define exactly how this relationship should work, or think about structuring it differently...

**Comment by michaelsproul** [comment]
Decisions:

* leave disconnects as is
* send votes to nodes from all current sections (disconnected or not)
* don't drop messages: just requeue them at the network layer
* seperate events from messages

**Comment by michaelsproul** [comment]
also:

* delete the connections container and refer to the nodes' local views of connections when working out what to disconect or reconnect

**Comment by michaelsproul** [comment]
Ticking all the boxes and closing this issue, as each point now has its own issue.
